#ifndef AYMOS_EDF_FIXTURE_H
#define AYMOS_EDF_FIXTURE_H

/* Shared by the native policy fixture and the real Cortex-M workload. */
enum {
    OS_EDF_FIXTURE_URGENT_ID = 1U,
    OS_EDF_FIXTURE_RELAXED_ID = 2U,
    OS_EDF_FIXTURE_URGENT_RELEASE = 5U,
    OS_EDF_FIXTURE_URGENT_PERIOD = 15U,
    OS_EDF_FIXTURE_URGENT_RELATIVE_DEADLINE = 10U,
    OS_EDF_FIXTURE_URGENT_FIRST_DEADLINE = 15U,
    OS_EDF_FIXTURE_URGENT_SECOND_RELEASE = 20U,
    OS_EDF_FIXTURE_URGENT_SECOND_DEADLINE = 30U,
    OS_EDF_FIXTURE_RELAXED_RELEASE = 0U,
    OS_EDF_FIXTURE_RELAXED_RELATIVE_DEADLINE = 50U,
    OS_EDF_FIXTURE_RELAXED_ABSOLUTE_DEADLINE = 50U,
    OS_EDF_FIXTURE_URGENT_PRIORITY = 1U,
    OS_EDF_FIXTURE_RELAXED_PRIORITY = 2U
};

#endif
